name: API

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:


  build:

    runs-on: ubuntu-latest
    
    env:
      MONGO_URL: ${{ secrets.MONGO_URL}}

    steps:
    - uses: actions/checkout@v3

    - name: Connect to docker
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Set tag name
      run: echo TAG=${{github.run_number}} >> $GITHUB_ENV
       
    - name: Build the Docker image
      run: |
        docker build --build-arg MONGO_URL=${MONGO_URL} -t ${{ secrets.DOCKER_USERNAME }}/mongo_api:"${TAG}" -f ./Dockerfile .
    - name: Push docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/mongo_api:${TAG}
        docker push ${{ secrets.DOCKER_USERNAME }}/mongo_api:latest
      