name: API

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Connect to docker
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Set tag name
      run: echo "TAG=14" >> $GITHUB_ENV
       
    - name: Build the Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/mongo_api:"${TAG}" -f ./Dockerfile .
    - name: Push docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/mongo_api:${TAG}
      