name: API

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Connect to docker
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Build the Docker image
      run: |
        TAG = "v1.0.${{ steps.get_build_number.outputs.BUILD_NUMBER }}"
        docker build . --file Dockerfile --tag ${TAG}
        echo "DOCKER_TAG=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
    - name: Push docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/mongo_api:${TAG}
      